package io.github.vadimbabich.entitymetamodel.processor.testing;

import static java.nio.charset.StandardCharsets.UTF_8;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;
import javax.annotation.processing.Processor;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.ToolProvider;

/**
 * Runs one annotation-processing round through {@code javax.tools} and nothing else.
 *
 * <p>The only class in the suite that touches a compiler API — everything else speaks outcomes and
 * bytes — so swapping the harness is a change here and nowhere else. It ships with the JDK, so no
 * new JDK can break the harness while leaving the product fine.
 */
public final class FixtureCompiler {

  private final Path workDirectory;
  private final List<Path> additionalClasspath;

  public FixtureCompiler(Path workDirectory, Path... additionalClasspath) {
    this.workDirectory = workDirectory;
    this.additionalClasspath = List.of(additionalClasspath);
  }

  public Path classOutput() {
    return workDirectory.resolve("classes");
  }

  public CompilationOutcome compile(List<Path> sources, Processor processor, String... options) {
    return compileWith(sources, List.of(processor), options);
  }

  /** Several processors in one compilation — how a type generated by another arrives. */
  public CompilationOutcome compileWith(
      List<Path> sources, List<Processor> processors, String... options) {

    try {
      return runRound(sources, processors, List.of(options));
    } catch (IOException e) {
      throw new UncheckedIOException("Compilation round could not be run", e);
    }
  }

  private CompilationOutcome runRound(
      List<Path> sources, List<Processor> processors, List<String> options) throws IOException {

    Path classOutput = Files.createDirectories(workDirectory.resolve("classes"));
    Path generatedSourceRoot = Files.createDirectories(workDirectory.resolve("generated-sources"));

    JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
    DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
    boolean succeeded;

    try (StandardJavaFileManager fileManager =
        compiler.getStandardFileManager(diagnostics, null, UTF_8)) {

      JavaCompiler.CompilationTask task = compiler.getTask(
          null,
          fileManager,
          diagnostics,
          compilerOptions(classOutput, generatedSourceRoot, options),
          null,
          fileManager.getJavaFileObjectsFromPaths(sources));

      task.setProcessors(processors);
      succeeded = task.call();
    }

    return new CompilationOutcome(
        succeeded, messagesOf(diagnostics), generatedSourcesUnder(generatedSourceRoot));
  }

  private List<String> compilerOptions(
      Path classOutput, Path generatedSourceRoot, List<String> extraOptions) {

    List<String> options = new ArrayList<>(List.of(
        // --release pins the language level so the JDK stays the only variable across the matrix.
        "--release", "17",
        "-encoding", "UTF-8",
        "-classpath", classpath(),
        "-d", classOutput.toString(),
        "-s", generatedSourceRoot.toString()));

    options.addAll(extraOptions);
    return options;
  }

  private String classpath() {
    StringBuilder classpath = new StringBuilder(System.getProperty("java.class.path"));

    for (Path entry : additionalClasspath) {
      classpath.append(File.pathSeparator).append(entry);
    }

    return classpath.toString();
  }

  private List<CompilationOutcome.Message> messagesOf(
      DiagnosticCollector<JavaFileObject> diagnostics) {

    List<CompilationOutcome.Message> messages = new ArrayList<>();

    for (var diagnostic : diagnostics.getDiagnostics()) {
      messages.add(new CompilationOutcome.Message(diagnostic.getKind(), diagnostic.toString()));
    }

    return List.copyOf(messages);
  }

  private Map<String, byte[]> generatedSourcesUnder(Path generatedSourceRoot) throws IOException {
    try (Stream<Path> generated = Files.walk(generatedSourceRoot)) {
      Map<String, byte[]> byRelativePath = new TreeMap<>();

      generated.filter(Files::isRegularFile)
          .forEach(file -> byRelativePath.put(
              relativePathOf(generatedSourceRoot, file), readBytes(file)));

      return Map.copyOf(byRelativePath);
    }
  }

  // Keys stay '/'-separated so a test's expected path reads the same on every platform.
  private String relativePathOf(Path root, Path file) {
    return root.relativize(file).toString().replace(File.separatorChar, '/');
  }

  private byte[] readBytes(Path file) {
    try {
      return Files.readAllBytes(file);
    } catch (IOException e) {
      throw new UncheckedIOException("Cannot read generated source " + file, e);
    }
  }
}
