// Generated by entity-metamodel – DO NOT EDIT. Any modifications will be overwritten.
package com.example.contract;

import io.github.vadimbabich.entitymetamodel.runtime.EntityRef;
import io.github.vadimbabich.entitymetamodel.runtime.Generated;
import io.github.vadimbabich.entitymetamodel.runtime.PropertyRef;

@Generated("io.github.vadimbabich.entitymetamodel")
public final class Account__ {
  public static final EntityRef<Account> ENTITY = EntityRef.of(Account.class);

  public static final PropertyRef<Account, Long> ID = ENTITY.property("id", Long.class);

  public static final PropertyRef<Account, String> NICKNAME = ENTITY.property("nickname", String.class);

  public static final PropertyRef<Account, String> OWNER_EMAIL = ENTITY.property("ownerEmail", String.class);

  public static final PropertyRef<Account, String> SOURCE_URL_PATH = ENTITY.property("sourceURLPath", String.class);

  private Account__() {
  }
}
