// Generated by entity-metamodel – DO NOT EDIT. Any modifications will be overwritten.
package com.example.contract;

import io.github.vadimbabich.entitymetamodel.runtime.EntityRef;
import io.github.vadimbabich.entitymetamodel.runtime.Generated;
import io.github.vadimbabich.entitymetamodel.runtime.PropertyRef;
import java.util.List;

@Generated("io.github.vadimbabich.entitymetamodel")
public final class Inventory__ {
  public static final EntityRef<Inventory> ENTITY = EntityRef.of(Inventory.class);

  public static final PropertyRef<Inventory, Long> ID = ENTITY.property("id", Long.class);

  public static final PropertyRef<Inventory, List<? extends Number>> LIMITS = ENTITY.property("limits", List.class);

  public static final PropertyRef<Inventory, int[]> SCORES = ENTITY.property("scores", int[].class);

  public static final PropertyRef<Inventory, List<String>> TAGS = ENTITY.property("tags", List.class);

  private Inventory__() {
  }
}
