// Generated by entity-metamodel – DO NOT EDIT. Any modifications will be overwritten.
package com.example.contract;

import io.github.vadimbabich.entitymetamodel.runtime.EntityRef;
import io.github.vadimbabich.entitymetamodel.runtime.Generated;
import io.github.vadimbabich.entitymetamodel.runtime.PropertyRef;

@Generated("io.github.vadimbabich.entitymetamodel")
public final class LegacyDocument__ {
  public static final EntityRef<LegacyDocument> ENTITY = EntityRef.of(LegacyDocument.class);

  public static final PropertyRef<LegacyDocument, String> CREATED_BY = ENTITY.property("createdBy", String.class);

  public static final PropertyRef<LegacyDocument, Long> ID = ENTITY.property("id", Long.class);

  public static final PropertyRef<LegacyDocument, Long> REVISION = ENTITY.property("revision", Long.class);

  public static final PropertyRef<LegacyDocument, String> TITLE = ENTITY.property("title", String.class);

  private LegacyDocument__() {
  }
}
