// Generated by entity-metamodel – DO NOT EDIT. Any modifications will be overwritten.
package com.example.contract;

import io.github.vadimbabich.entitymetamodel.runtime.EntityRef;
import io.github.vadimbabich.entitymetamodel.runtime.Generated;
import io.github.vadimbabich.entitymetamodel.runtime.PropertyRef;
import java.time.Instant;
import java.time.LocalDate;

@Generated("io.github.vadimbabich.entitymetamodel")
public final class Payment__ {
  public static final EntityRef<Payment> ENTITY = EntityRef.of(Payment.class);

  public static final PropertyRef<Payment, Boolean> CAPTURED = ENTITY.property("captured", boolean.class);

  public static final PropertyRef<Payment, Instant> CAPTURED_AT = ENTITY.property("capturedAt", Instant.class);

  public static final PropertyRef<Payment, Long> ID = ENTITY.property("id", long.class);

  public static final PropertyRef<Payment, Integer> RETRY_COUNT = ENTITY.property("retryCount", int.class);

  public static final PropertyRef<Payment, LocalDate> SETTLED_ON = ENTITY.property("settledOn", LocalDate.class);

  public static final PropertyRef<Payment, PaymentStatus> STATUS = ENTITY.property("status", PaymentStatus.class);

  private Payment__() {
  }
}
