// Generated by entity-metamodel – DO NOT EDIT. Any modifications will be overwritten.
package com.example.contract;

import io.github.vadimbabich.entitymetamodel.runtime.EntityRef;
import io.github.vadimbabich.entitymetamodel.runtime.Generated;
import io.github.vadimbabich.entitymetamodel.runtime.PropertyRef;

@Generated("io.github.vadimbabich.entitymetamodel")
public final class Vendor__ {
  public static final EntityRef<Vendor> ENTITY = EntityRef.of(Vendor.class);

  public static final PropertyRef<Vendor, String> DISPLAY_NAME = ENTITY.property("displayName", String.class);

  public static final PropertyRef<Vendor, Long> ID = ENTITY.property("id", Long.class);

  public static final class VendorPermissionView__ {
    public static final EntityRef<Vendor.VendorPermissionView> ENTITY = EntityRef.of(Vendor.VendorPermissionView.class);

    public static final PropertyRef<Vendor.VendorPermissionView, Long> ID = ENTITY.property("id", Long.class);

    public static final PropertyRef<Vendor.VendorPermissionView, String> PERMISSION_KEY = ENTITY.property("permissionKey", String.class);

    public static final PropertyRef<Vendor.VendorPermissionView, Long> VENDOR_ID = ENTITY.property("vendorId", Long.class);

    private VendorPermissionView__() {
    }
  }

  private Vendor__() {
  }
}
