// Generated by entity-metamodel – DO NOT EDIT. Any modifications will be overwritten.
package com.example.contract;

import io.github.vadimbabich.entitymetamodel.runtime.EntityRef;
import io.github.vadimbabich.entitymetamodel.runtime.Generated;
import io.github.vadimbabich.entitymetamodel.runtime.PropertyRef;

@Generated("io.github.vadimbabich.entitymetamodel")
public final class Wrapper_Attachment__ {
  public static final EntityRef<Wrapper.Attachment> ENTITY = EntityRef.of(Wrapper.Attachment.class);

  public static final PropertyRef<Wrapper.Attachment, String> FILE_NAME = ENTITY.property("fileName", String.class);

  public static final PropertyRef<Wrapper.Attachment, Long> ID = ENTITY.property("id", Long.class);

  private Wrapper_Attachment__() {
  }
}
