package io.github.vadimbabich.entitymetamodel.processor.emit;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Writes one planned unit as source text.
 *
 * <p>Assembled here rather than by a code-generation library because the contract fixes the member
 * order — nested metamodels before the private constructor — while the libraries impose an order of
 * their own, and byte parity is the acceptance gate. Five constructs, no control flow.
 */
final class MetamodelWriter {

  private static final String HEADER =
      "// Generated by entity-metamodel – DO NOT EDIT. Any modifications will be overwritten.";

  // Deliberately not a generator class name: the value is part of the frozen shape, so any frontend
  // emitting this contract produces the same bytes.
  private static final String GENERATOR_ID = "io.github.vadimbabich.entitymetamodel";

  private static final String GENERATED = MetamodelSourceGenerator.GENERATED_ANNOTATION;
  private static final String ENTITY_REF =
      "io.github.vadimbabich.entitymetamodel.runtime.EntityRef";
  private static final String PROPERTY_REF =
      "io.github.vadimbabich.entitymetamodel.runtime.PropertyRef";

  private static final String INDENT = "  ";
  // Package-private: the planner rejects any property that maps to this name.
  static final String ENTITY_MEMBER = "ENTITY";

  private final ExistingTypes existingTypes;

  MetamodelWriter(ExistingTypes existingTypes) {
    this.existingTypes = existingTypes;
  }

  String write(MetamodelUnit unit) {
    ImportScope scope = ImportScope.of(
        unit.packageName(), referencedTypesOf(unit), declaredNamesOf(unit.root()), existingTypes);

    StringBuilder source = new StringBuilder();

    source.append(HEADER).append('\n');

    // An entity in the default package is unusual but legal, and "package ;" would not compile.
    if (!unit.packageName().isEmpty()) {
      source.append("package ").append(unit.packageName()).append(";\n\n");
    }

    for (String imported : scope.imports()) {
      source.append("import ").append(imported).append(";\n");
    }
    if (!scope.imports().isEmpty()) {
      source.append('\n');
    }

    source.append('@').append(scope.render(GENERATED))
        .append("(\"").append(GENERATOR_ID).append("\")\n");
    source.append("public final class ").append(unit.root().simpleName()).append(" {\n");
    appendMembers(source, unit.root(), scope, 1);
    source.append("}\n");

    return source.toString();
  }

  private void appendMembers(
      StringBuilder source, MetamodelClass metamodel, ImportScope scope, int depth) {

    List<String> members = new ArrayList<>();

    members.add(entityMember(metamodel, scope, depth));

    for (MetamodelProperty property : metamodel.properties()) {
      members.add(propertyMember(metamodel, property, scope, depth));
    }
    for (MetamodelClass nested : metamodel.nested()) {
      members.add(nestedMember(nested, scope, depth));
    }

    members.add(privateConstructor(metamodel, depth));

    source.append(String.join("\n", members));
  }

  private String entityMember(MetamodelClass metamodel, ImportScope scope, int depth) {
    String entityType = metamodel.entityTypeName();

    return indent(depth) + "public static final " + scope.render(ENTITY_REF) + "<" + entityType
        + "> " + ENTITY_MEMBER + " = " + scope.render(ENTITY_REF) + ".of(" + entityType
        + ".class);\n";
  }

  private String propertyMember(
      MetamodelClass metamodel, MetamodelProperty property, ImportScope scope, int depth) {

    String entityType = metamodel.entityTypeName();
    String valueType = TypeText.render(property.valueType(), scope);
    String rawType = TypeText.render(property.rawType(), scope);

    return indent(depth) + "public static final " + scope.render(PROPERTY_REF) + "<" + entityType
        + ", " + valueType + "> " + property.constantName() + " = " + ENTITY_MEMBER + ".property(\""
        + property.propertyName() + "\", " + rawType + ".class);\n";
  }

  private String nestedMember(MetamodelClass nested, ImportScope scope, int depth) {
    StringBuilder member = new StringBuilder();

    member.append(indent(depth)).append("public static final class ")
        .append(nested.simpleName()).append(" {\n");
    appendMembers(member, nested, scope, depth + 1);
    member.append(indent(depth)).append("}\n");

    return member.toString();
  }

  private String privateConstructor(MetamodelClass metamodel, int depth) {
    return indent(depth) + "private " + metamodel.simpleName() + "() {\n" + indent(depth) + "}\n";
  }

  private Set<String> referencedTypesOf(MetamodelUnit unit) {
    Set<String> referenced = new LinkedHashSet<>(List.of(GENERATED, ENTITY_REF, PROPERTY_REF));

    collectReferencedTypes(unit.root(), referenced);
    return referenced;
  }

  private void collectReferencedTypes(MetamodelClass metamodel, Set<String> referenced) {
    for (MetamodelProperty property : metamodel.properties()) {
      TypeText.collectReferences(property.valueType(), referenced);
      TypeText.collectReferences(property.rawType(), referenced);
    }
    for (MetamodelClass nested : metamodel.nested()) {
      collectReferencedTypes(nested, referenced);
    }
  }

  private Set<String> declaredNamesOf(MetamodelClass metamodel) {
    Set<String> declared = new LinkedHashSet<>();

    declared.add(metamodel.simpleName());
    declared.add(metamodel.entityRootName());
    for (MetamodelClass nested : metamodel.nested()) {
      declared.addAll(declaredNamesOf(nested));
    }

    return declared;
  }

  private String indent(int depth) {
    return INDENT.repeat(depth);
  }
}
